name: Create release

on:
  workflow_dispatch:
    inputs:
      DEPLOY_VERSION:
        description: 'Version to deploy'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_APIKEY }}
        with:
          tag_name: ${{ github.event.inputs.DEPLOY_VERSION }}
          release_name: ${{ github.event.inputs.DEPLOY_VERSION }}
          body: |
            Changes in this Release
            - Working on change list. Check back soon.
          draft: false
